version: 3.10.12

networks:
  app-network:

services:
  backend:
    build: .
    volumes:
      - ..:/FastAPI_REF
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DB_URL=postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=5000
      - REDIS_URL=redis://{REDIS_HOST}:{REDIS_PORT}
    command: uvicorn src.main:app --reload --workers 5 --host 0.0.0.0 --port 8080
    depends_on:
      - database
      - redis

  database:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DB_URL=postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}

    networks:
      - app-network
    ports:
      - "25432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=5000
      - REDIS_URL=redis://{REDIS_HOST}:{REDIS_PORT}
    networks:
      - app-network
volumes:
  postgres_data: