services:
  backend:
    build: .
    volumes:
      - ./:/usr/app/.
    container_name: app_backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: bash -c 'alembic upgrade head && python -m src.main'
    depends_on:
      - database
      - redis
    expose:
      - 8000

  database:
    image: postgres:latest
    container_name: app-database
    restart: always
    networks:
      - app-network
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:latest
    container_name: app-redis
    restart: always
    networks:
      - app-network

networks:
  app-network:
